Fixed a bug with current directories.

diff --git a/bin/mae-create-pack b/bin/mae-create-pack
--- a/bin/mae-create-pack
+++ b/bin/mae-create-pack
@@ -1,4 +1,12 @@
 #! /bin/bash
-source "$(dirname "$0")/../lib/mae-lib-general.sh" || { echo "fatal error: cannot load magic ecabu library"; exit 13; }
-echo "done"
+p="$(pwd)"
+cd "$(dirname "$0")/.."
+base_dir="$(pwd)"
+cd "$p"
+source "$base_dir/lib/mae-lib-general.sh" ||
+  { echo "fatal error: cannot load magic ecabu library"; exit 13; }
 
+mkdir -p "$packs_dir"
+sha1="$(java -jar "$base_dir/lib/java/packwriter.jar" -d "$packs_dir")" ||
+  die "packwriter failed."
+echo "$sha1"
